# variables for the webservers group

    db_users:
      - test
      - dev
      - qa

    # username: 
    #   test:
    #     uname: test
    #     description: Test User Account
    #     # password: "{{ secret }}"