control:
  hosts:
    mint:
      ansible_connection: local
      ansible_ssh_host: robq@192.168.0.48

webservers:
  hosts:
    centos3:
      ansible_ssh_host: 192.168.0.47
  vars:
    ansible_user: packt

databases:
  hosts:
    centos2:
      ansible_ssh_host: 192.168.0.46
  vars:
    ansible_user: packt

# mint ansible_ssh_host=robq@192.168.0.48
# centos1 ansible_ssh_host=packt@192.168.0.45
# centos2 ansible_ssh_host=packt@192.168.0.46
# centos3 ansible_ssh_host=packt@192.168.0.47
