---
- name: Gathers facts for webservers
  hosts: webservers
  tasks:
  - setup:
      gather_subset: 
        - "all"
  tags:
    - all

- name: Run conditional Task
  include: conditional.yml

- name: Handling Errors with Block (Block, Rescue & Always)
  include: block_rescue_always.yml