---
# YAML documents begin with the document separator ---
 
# The minus in YAML this indicates a list item.  The playbook contains a list
# of plays, with each play being a dictionary
 
  # Target: where our play will run and options it will run with
- name: Gathers facts for webservers
  hosts: webservers
  tasks:
  - setup:
      gather_subset: 
        - "all"
  tags:
    - all
  
- name: Create New User
  hosts: webservers
  become: true
  tasks:
    - name: User created
      user:
        name: test2
        state: present