---
# YAML documents begin with the document separator ---
 
# The minus in YAML this indicates a list item.  The playbook contains a list
# of plays, with each play being a dictionary
 
  # Target: where our play will run and options it will run with
- name: Gathers facts for webservers & databases
  hosts: webservers databases
  tasks:
  - setup:
      gather_subset: 
        - "all"
  tags:
    - all
  
# - name: Create New User
#   hosts: webservers databases
#   become: true

- name: Create multiple Users
  hosts: webservers databases
  become: true
  vars:
    myusers:
      - rita
      - sue
      - bob

# - name: Create Users in Groups
#   hosts: webservers databases
#   become: true
  
  tasks:
  #   - name: Load variable from encrypted file
  #     include_vars:
  #       file: secret

  #   - name: Display contents of encrypted file
  #     debug:
  #       msg: "{{ secret }}"
  #     no_log: true

    # - name: User created
    #   user:
    #     name: "{{ username['test']['uname'] }}"
    #     comment: "{{ username['test']['description'] }}"
    #     # password: "{{ username['test']['password'] }}"
    #     state: present
    
    - name: Looping through creating the Users
      user:
        name: "{{ item }}"
        state: present
      loop: "{{ myusers }}"

    # - name: Create Groups
    #   group:
    #     name: "{{ item }}"
    #     state: present
    #   loop:
    #     - flintstones
    #     - rubbles

    # - name: Create User in their appropiate Groups
    #   user:
    #     name: "{{ item.name }}"
    #     groups: "{{ item.groups }}"
    #   with_dict:
    #     - { name: 'fred', groups: 'flintstones' }
    #     - { name: 'wilma', groups: 'flintstones' }
    #     - { name: 'barney', groups: 'rubbles' }
    #     - { name: 'dave', groups: 'rubbles' }
